**Classification Case Study
PREDICTION OF HEART DISEASE BASED ON VARIOUS FEATURES

 This dataset has 270 rows. We have to build and train a model on this dataset so it can predict whether the person will have heart disease or not based on age,bp, cholestral

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import os
os.chdir('D:\\ML\\2023 ML\\LAB')

**LOAD THE DATA SET

In [2]:
os.getcwd()

'D:\\ML\\2023 ML\\LAB'

In [3]:
df=pd.read_csv("heart_v2.csv")
#we are loading the CSV file and also we are converting the CSV file 
# to the pandas data frame

In [4]:
df

     age  sex   BP  cholestrol  heart disease
0     70    1  130         322              1
1     67    0  115         564              0
2     57    1  124         261              1
3     64    1  128         263              0
4     74    0  120         269              0
..   ...  ...  ...         ...            ...
265   52    1  172         199              0
266   44    1  120         263              0
267   56    0  140         294              0
268   57    1  140         192              0
269   67    1  160         286              1

[270 rows x 5 columns]

**2 ANALYZE THE DATA SET

The dataset contains 5 columns

In [5]:
#there are 270 rows and 5 columns
df.shape

(270, 5)

In [6]:
df.dtypes

age              int64
sex              int64
BP               int64
cholestrol       int64
heart disease    int64
dtype: object

This method returns the output below. It basically shows the number of entries, the column names and the column types. Below is the output of the command.

In [7]:
## To check the data type of the variable
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            270 non-null    int64
 1   sex            270 non-null    int64
 2   BP             270 non-null    int64
 3   cholestrol     270 non-null    int64
 4   heart disease  270 non-null    int64
dtypes: int64(5)
memory usage: 10.7 KB
None

**check for empty values This method is basically used to check if there are any null values in the dataset. This will list number of null values in each column

Below is the output of the command. We can see that there are no null values in any of the columns.

In [8]:
cnt=df.isnull().sum()
print(" Data columns with null values ",cnt)

 Data columns with null values  age              0
sex              0
BP               0
cholestrol       0
heart disease    0
dtype: int64

In [8]:
## It shows that the above data set does not contain NULL VALUES

In [9]:
#TO GET THE NUMERICAL VARIABLES
numerical_features=(df.select_dtypes(include=['int64','float64']).columns.values)
numerical_features

array(['age', 'sex', 'BP', 'cholestrol', 'heart disease'], dtype=object)

In [10]:
#TO GET THE categorical VARIABLES
categorical_features=(df.select_dtypes(include=['object']).columns.values)
categorical_features

array([], dtype=object)

In [11]:
df.dtypes

age              int64
sex              int64
BP               int64
cholestrol       int64
heart disease    int64
dtype: object

In [12]:
df.tail(5)

     age  sex   BP  cholestrol  heart disease
265   52    1  172         199              0
266   44    1  120         263              0
267   56    0  140         294              0
268   57    1  140         192              0
269   67    1  160         286              1

In [13]:
df.head()

   age  sex   BP  cholestrol  heart disease
0   70    1  130         322              1
1   67    0  115         564              0
2   57    1  124         261              1
3   64    1  128         263              0
4   74    0  120         269              0

Divide the data into train and test
Step 4: Split dataset into training set and test set

In [14]:
from sklearn.model_selection import train_test_split

Every data set has input as well as output variables. In this case study, Weight and Height are our input variables. And “Gender” is our output variable. So let's separate our data frame df into X and y. X will store the input variable. y will store the output variable.

Drop the Target or output variable. we have to identify the gender of the variable based on height and weight so drop the gender variable

In [15]:
X=df.drop('heart disease',axis=1)
y=df['heart disease']

In [16]:
X

     age  sex   BP  cholestrol
0     70    1  130         322
1     67    0  115         564
2     57    1  124         261
3     64    1  128         263
4     74    0  120         269
..   ...  ...  ...         ...
265   52    1  172         199
266   44    1  120         263
267   56    0  140         294
268   57    1  140         192
269   67    1  160         286

[270 rows x 4 columns]

In [17]:
y

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: heart disease, Length: 270, dtype: int64

Now, to proceed further we have to divide our data into the training part and testing part. Training part will be used to train our model. The testing part will be used to test our model whether it gives correct predictions or not. and also to measure the model's performance. So divide X and y into X_train,X_test and y_train,y_test respectively.

In [18]:
# Now call train_test_split function and pass X,y to divide them 
# into 4 parts as X_train,X_test and y_train,y_test
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=0)
# test size is 0.2 that is 20% so train size will be 80% automatically.
# random state is 112 or any numeric number. 
# Every random state number has a different fashion to select data rows randomly.
# random_state simply sets seed to the random generator, 
# so that your train-test splits are always deterministic.

Now we have to enter into 3rd phase of Machine learning life cycle. In this phase, we apply an algorithm to our dataset. So that our model gets trained and able to observe and analyse patterns within data. So lets apply DecisionTreeClassifier algorithm in this case study.

Step 5: Fit Classification Model

In [22]:
# LOGISTIC REGRESSION

In [19]:
from sklearn.linear_model import LogisticRegression
Logit_Model=LogisticRegression() #solver='lbfgs', max_iter=200)
Logit_Model.fit(X_train,y_train)
ans=Logit_Model.score(X_train,y_train)
print("The logistic Regression Training score",ans*100)

The logistic Regression Training score 67.1957671957672

In [20]:

#EVALUATION METRICS
from sklearn.metrics import accuracy_score 
prediction=Logit_Model.predict(X_test)
score = accuracy_score(y_test,prediction)
print("The logistic Regression Testing score",score*100)

The logistic Regression Testing score 65.4320987654321

In [22]:
disease_pred = Logit_Model.predict([[67,1,160,286]])
print("My Predicted Value is is ",disease_pred)

My Predicted Value is is  [1]

D:\anaconda1\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(